using Compile.Shift.Ef;
using FluentAssertions;
using static Compile.Shift.Ef.Tests.TestModels;

namespace Compile.Shift.Ef.Tests;

/// <summary>
/// Tests for <see cref="EntityGenerator"/>.
///
/// Intent: produce a POCO entity class per table with:
///  - an auto-generated header and data-annotation usings,
///  - a [Table(name)] attribute and `public partial class {Name}Entity`,
///  - one property per field carrying [Column], and where applicable [Key],
///    [DatabaseGenerated(Identity)], [Required] and a decimal type-name,
///  - a navigation property per foreign key with a [ForeignKey] attribute.
/// </summary>
public class EntityGeneratorTests
{
    private readonly EntityGenerator _sut = new();

    [Fact]
    public void GenerateEntity_EmitsHeaderUsingsNamespaceAndClassDeclaration()
    {
        var table = Table("User", new[] { Field("Id", "int", primaryKey: true, identity: true) });

        var code = _sut.GenerateEntity(table, "My.Namespace");

        code.Should().Contain("// <auto-generated />");
        code.Should().Contain("using System.ComponentModel.DataAnnotations;");
        code.Should().Contain("using System.ComponentModel.DataAnnotations.Schema;");
        code.Should().Contain("namespace My.Namespace;");
        code.Should().Contain("[Table(\"User\")]");
        code.Should().Contain("public partial class UserEntity");
    }

    [Fact]
    public void GenerateEntity_SimpleProperty_HasColumnAttributeAndTypedProperty()
    {
        var table = Table("User", new[] { Field("Username", "nvarchar", precision: 100) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[Column(\"Username\")]");
        code.Should().Contain("public string Username { get; set; }");
    }

    [Fact]
    public void GenerateEntity_PrimaryKeyIdentity_AddsKeyAndDatabaseGenerated()
    {
        var table = Table("User", new[] { Field("Id", "int", primaryKey: true, identity: true) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[Key]");
        code.Should().Contain("[DatabaseGenerated(DatabaseGeneratedOption.Identity)]");
        code.Should().Contain("public int Id { get; set; }");
    }

    [Fact]
    public void GenerateEntity_NonNullableValueType_IsMarkedRequired()
    {
        var table = Table("Order", new[] { Field("Quantity", "int") });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[Required]");
        code.Should().Contain("public int Quantity { get; set; }");
    }

    [Fact]
    public void GenerateEntity_NonNullableString_IsNotMarkedRequired()
    {
        // Intent: strings are excluded from [Required] (the type itself conveys requiredness in EF).
        var table = Table("User", new[] { Field("Username", "nvarchar", precision: 100) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().NotContain("[Required]");
    }

    [Fact]
    public void GenerateEntity_NullableValueType_IsNotRequiredAndNullableProperty()
    {
        var table = Table("User", new[] { Field("LastLogin", "datetime", nullable: true) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().NotContain("[Required]");
        code.Should().Contain("public DateTime? LastLogin { get; set; }");
    }

    [Fact]
    public void GenerateEntity_DecimalWithPrecisionAndScale_EmitsTypeNameInColumnAttribute()
    {
        var table = Table("Product", new[] { Field("Price", "decimal", precision: 18, scale: 2) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[Column(\"Price\", TypeName = \"decimal(18,2)\")]");
    }

    [Fact]
    public void GenerateEntity_DecimalWithPrecisionOnly_EmitsTypeNameWithoutScale()
    {
        var table = Table("Product", new[] { Field("Weight", "decimal", precision: 9) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[Column(\"Weight\", TypeName = \"decimal(9)\")]");
    }

    [Fact]
    public void GenerateEntity_ForeignKey_EmitsNavigationPropertyWithForeignKeyAttribute()
    {
        var table = Table(
            "Order",
            fields: new[] { Field("CustomerId", "int") },
            foreignKeys: new[] { ForeignKey("CustomerId", "Customer") });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("[ForeignKey(\"CustomerId\")]");
        code.Should().Contain("public virtual CustomerEntity Customer { get; set; }");
    }

    [Fact]
    public void GenerateEntity_NullableForeignKey_NavigationPropertyIsNullable()
    {
        var table = Table(
            "Order",
            fields: new[] { Field("CustomerId", "int", nullable: true) },
            foreignKeys: new[] { ForeignKey("CustomerId", "Customer", nullable: true) });

        var code = _sut.GenerateEntity(table, "N");

        code.Should().Contain("public virtual CustomerEntity? Customer { get; set; }");
    }
}