using Compile.Shift.Helpers;
using Compile.Shift.Model;
using Compile.Shift.Model.Helpers;
using Compile.Shift.Plugins;
using Microsoft.Extensions.Logging;
using System.Text;
using System.Text.RegularExpressions;

namespace Compile.Shift.Dbml;

public interface IDbmlExporter : IShiftPlugin
{
    /// <summary>
    /// Renders the whole model as a single DBML document.
    /// </summary>
    string GenerateDbml(DatabaseModel model);

    /// <summary>
    /// Renders the model and writes it to <paramref name="outputPath"/>, returning the file written.
    /// </summary>
    Task<string> ExportAsync(DatabaseModel model, string outputPath);
}

/// <summary>
/// Exports a <see cref="DatabaseModel"/> as a DBML document for https://dbdiagram.io.
///
/// The diagram is shaped by the <c>erd-*</c> plugin attributes listed in
/// <see cref="DbmlErdAttributes"/>; everything else comes from the model itself. Each diagram
/// concern is routed through a single private resolver so there is exactly one place to change when
/// its policy changes.
/// </summary>
public class DbmlExporter : IDbmlExporter
{
    internal const string DbmlFileExtension = ".dbml";

    /// <summary>
    /// The file name used when the output path names a directory. It is a compile-time constant on
    /// purpose: nothing derived from a table name, column name or attribute value is ever allowed to
    /// influence the path that gets written.
    /// </summary>
    internal const string DefaultFileName = "model" + DbmlFileExtension;

    // DBML accepts a bare identifier of this shape; anything else has to be double-quoted.
    private static readonly Regex DbmlIdentifierRegex =
        new(@"^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);

    private static readonly Regex ColorRegex =
        new(@"^#?([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$", RegexOptions.Compiled);

    private static readonly Regex NonIdentifierRunRegex =
        new(@"[^A-Za-z0-9_]+", RegexOptions.Compiled);

    private readonly DbmlTypeMapper _typeMapper = new();

    public required ILogger Logger { private get; init; }

    public string Name => "dbml";

    public string Description => "Exports the model as a DBML diagram for dbdiagram.io";

    public IReadOnlyList<PluginAttributeDefinition> SupportedAttributes { get; } =
    [
        new PluginAttributeDefinition(
            DbmlErdAttributes.Hide,
            AttributeScope.Both,
            IsFlag: true,
            "Omits the table (with its relationships and group membership) or the column from the diagram"),
        new PluginAttributeDefinition(
            DbmlErdAttributes.Group,
            AttributeScope.Model,
            IsFlag: false,
            "Puts the table in the named TableGroup; ignored on a field because DBML has no column groups"),
        new PluginAttributeDefinition(
            DbmlErdAttributes.Note,
            AttributeScope.Both,
            IsFlag: false,
            "Adds the text as a DBML note on the table or column"),
        new PluginAttributeDefinition(
            DbmlErdAttributes.Color,
            AttributeScope.Model,
            IsFlag: false,
            "Sets the table header colour, as rgb or rrggbb hex digits"),
    ];

    public async Task<string> ExportAsync(DatabaseModel model, string outputPath)
    {
        var (directory, filePath) = ResolveOutputPath(outputPath);

        Directory.CreateDirectory(directory);

        var dbml = GenerateDbml(model);
        await File.WriteAllTextAsync(filePath, dbml);

        Logger.LogInformation("Wrote DBML for {TableCount} tables to {FilePath}", model.Tables.Count, filePath);

        return filePath;
    }

    public string GenerateDbml(DatabaseModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Shift. Paste into https://dbdiagram.io to view the diagram.");

        var visibleTables = model.Tables.Values
            .Where(table => !IsHidden(table.Attributes))
            .OrderBy(table => table.Name, StringComparer.Ordinal)
            .ToList();

        var visibleColumnsByTable = visibleTables.ToDictionary(
            table => table.Name,
            table => table.Fields
                .Where(field => !IsHidden(field.Attributes))
                .Select(field => field.Name)
                .ToHashSet(StringComparer.OrdinalIgnoreCase),
            StringComparer.OrdinalIgnoreCase);

        foreach (var table in visibleTables)
        {
            AppendTable(sb, table, visibleColumnsByTable[table.Name]);
        }

        AppendRelationships(sb, visibleTables, visibleColumnsByTable);
        AppendTableGroups(sb, visibleTables);

        return sb.ToString();
    }

    // ---- tables --------------------------------------------------------------

    private void AppendTable(StringBuilder sb, TableModel table, HashSet<string> visibleColumns)
    {
        sb.AppendLine();
        sb.AppendLine($"Table {EscapeIdentifier(table.Name)}{RenderTableSettings(table)} {{");

        // Filtered on the field's own attributes rather than through visibleColumns, so a hidden
        // field is dropped even in a model that carries two fields whose names differ only in case.
        foreach (var field in table.Fields.Where(f => !IsHidden(f.Attributes)))
        {
            AppendColumn(sb, table, field);
        }

        AppendIndexes(sb, table, visibleColumns);

        var note = table.Attributes.AttributeValue(DbmlErdAttributes.Note);
        if (!string.IsNullOrWhiteSpace(note))
        {
            sb.AppendLine();
            sb.AppendLine($"  Note: {QuoteString(note)}");
        }

        sb.AppendLine("}");
    }

    private void AppendColumn(StringBuilder sb, TableModel table, FieldModel field)
    {
        if (!_typeMapper.TryMapToDbmlType(field, out var columnType))
        {
            Logger.LogDebug(
                "Column {TableName}.{ColumnName} has type {TypeName}, which Shift does not model; emitting it verbatim",
                table.Name, field.Name, field.Type);
        }

        var settings = new List<string>();

        if (field.IsPrimaryKey)
        {
            settings.Add("pk");

            if (field.IsIdentity)
            {
                settings.Add("increment");
            }
        }

        // DBML columns are nullable by default, so only the non-nullable case needs saying.
        if (!field.IsNullable)
        {
            settings.Add("not null");
        }

        if (HasSingleColumnUniqueIndex(table, field.Name))
        {
            settings.Add("unique");
        }

        var note = field.Attributes.AttributeValue(DbmlErdAttributes.Note);
        if (!string.IsNullOrWhiteSpace(note))
        {
            settings.Add($"note: {QuoteString(note)}");
        }

        var renderedSettings = settings.Count > 0 ? $" [{string.Join(", ", settings)}]" : string.Empty;

        sb.AppendLine($"  {EscapeIdentifier(field.Name)} {columnType}{renderedSettings}");
    }

    private static void AppendIndexes(StringBuilder sb, TableModel table, HashSet<string> visibleColumns)
    {
        var indexes = ResolveIndexes(table, visibleColumns)
            .Where(index => !(index.IsUnique && index.Fields.Count == 1))
            .ToList();

        if (indexes.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("  indexes {");

        foreach (var index in indexes)
        {
            var columns = index.Fields.Select(EscapeIdentifier).ToList();

            // DBML spells a single-column index bare and a composite one in parentheses.
            var target = columns.Count == 1 ? columns[0] : $"({string.Join(", ", columns)})";
            var settings = index.IsUnique ? " [unique]" : string.Empty;

            sb.AppendLine($"    {target}{settings}");
        }

        sb.AppendLine("  }");
    }

    /// <summary>
    /// The table's indexes with their field names resolved from model names to column names, keeping
    /// only indexes whose every column is visible. An index naming a hidden column would be a DBML
    /// parse error, the same hazard as a dangling relationship.
    /// </summary>
    private static List<IndexModel> ResolveIndexes(TableModel table, HashSet<string> visibleColumns)
    {
        return table.Indexes
            .Select(index => new IndexModel
            {
                Fields = IndexFieldResolver.ResolveIndexFieldNames(index.Fields, table),
                IsUnique = index.IsUnique,
                IsAlternateKey = index.IsAlternateKey,
                Kind = index.Kind
            })
            .Where(index => index.Fields.Count > 0 && index.Fields.All(visibleColumns.Contains))
            // The model can carry the same index twice (the DMD exporter dedupes for the same
            // reason); a repeated index definition is not valid DBML.
            .DistinctBy(index => $"{index.IsUnique}:{string.Join(",", index.Fields).ToLowerInvariant()}")
            .ToList();
    }

    private static bool HasSingleColumnUniqueIndex(TableModel table, string columnName)
    {
        return table.Indexes.Any(index =>
            index.IsUnique &&
            index.Fields.Count == 1 &&
            string.Equals(
                IndexFieldResolver.ResolveIndexFieldNames(index.Fields, table)[0],
                columnName,
                StringComparison.OrdinalIgnoreCase));
    }

    private static string RenderTableSettings(TableModel table)
    {
        var color = table.Attributes.AttributeValue(DbmlErdAttributes.Color);

        if (string.IsNullOrWhiteSpace(color))
        {
            return string.Empty;
        }

        var match = ColorRegex.Match(color.Trim());

        if (!match.Success)
        {
            throw new InvalidOperationException(
                $"Invalid @{DbmlErdAttributes.Color} value '{color}' on model '{table.Name}'. Expected 3 or 6 hex digits, such as 3498DB or 38D.");
        }

        return $" [headercolor: #{match.Groups[1].Value}]";
    }

    // ---- relationships -------------------------------------------------------

    /// <summary>
    /// One short-form <c>Ref:</c> per foreign key, emitted after every table because a Ref naming a
    /// table that has not been declared is a DBML parse error. Refs are oriented so the foreign key
    /// is always the second column, which is the side DBML treats as the FK.
    /// </summary>
    private static void AppendRelationships(
        StringBuilder sb,
        List<TableModel> visibleTables,
        Dictionary<string, HashSet<string>> visibleColumnsByTable)
    {
        var refs = new List<string>();

        foreach (var table in visibleTables)
        {
            foreach (var fk in table.ForeignKeys.OrderBy(x => x.ColumnName, StringComparer.Ordinal))
            {
                // Drop anything that would dangle: a hidden target table, a hidden FK column, or a
                // hidden target column.
                if (!visibleColumnsByTable.TryGetValue(fk.TargetTable, out var targetColumns) ||
                    !visibleColumnsByTable[table.Name].Contains(fk.ColumnName) ||
                    !targetColumns.Contains(fk.TargetColumnName))
                {
                    continue;
                }

                var cardinality = fk.RelationshipType == RelationshipType.OneToMany ? "<" : "-";

                refs.Add(
                    $"Ref: {EscapeIdentifier(fk.TargetTable)}.{EscapeIdentifier(fk.TargetColumnName)} " +
                    $"{cardinality} {EscapeIdentifier(table.Name)}.{EscapeIdentifier(fk.ColumnName)}");
            }
        }

        if (refs.Count == 0)
        {
            return;
        }

        sb.AppendLine();

        foreach (var reference in refs)
        {
            sb.AppendLine(reference);
        }
    }

    // ---- groups --------------------------------------------------------------

    private static void AppendTableGroups(StringBuilder sb, List<TableModel> visibleTables)
    {
        // Grouped by the DBML identifier, not by the raw @erd-group value: two distinct values can
        // slugify to the same identifier ('Billing Ops' and Billing_Ops both give Billing_Ops), and
        // two TableGroup blocks sharing one name is a DBML parse error that takes the whole document
        // with it. Names DBML cannot tell apart therefore become one group rather than two blocks.
        var groups = visibleTables
            .Select(table => (Table: table, Group: ResolveGroup(table)?.Trim()))
            .Where(x => !string.IsNullOrWhiteSpace(x.Group))
            .GroupBy(x => SlugifyGroupName(x.Group!), StringComparer.OrdinalIgnoreCase)
            .OrderBy(group => group.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();

        foreach (var group in groups)
        {
            var identifier = group.Key;

            // The slug is what DBML can name; when it differs from what the author wrote, the
            // original is kept in a note so the human string is not lost. Where several originals
            // collapsed onto one slug, the first in sorted order is used so the output is stable.
            var original = group
                .Select(x => x.Group!)
                .OrderBy(name => name, StringComparer.Ordinal)
                .First();

            var settings = string.Equals(identifier, original, StringComparison.Ordinal)
                ? string.Empty
                : $" [note: {QuoteString(original)}]";

            sb.AppendLine();
            sb.AppendLine($"TableGroup {EscapeIdentifier(identifier)}{settings} {{");

            foreach (var member in group.Select(x => x.Table.Name).OrderBy(name => name, StringComparer.Ordinal))
            {
                sb.AppendLine($"  {EscapeIdentifier(member)}");
            }

            sb.AppendLine("}");
        }
    }

    /// <summary>
    /// The group a table belongs to, or null when it belongs to none. This is the single seam for
    /// group resolution: a future fallback (deriving the group from the .dmd folder structure, say)
    /// belongs here and must only be consulted when no explicit <c>@erd-group</c> is present, so an
    /// explicit attribute always wins.
    /// </summary>
    private static string? ResolveGroup(TableModel table)
    {
        return table.Attributes.AttributeValue(DbmlErdAttributes.Group);
    }

    /// <summary>
    /// The group name as a bare DBML identifier. Collapsing the non-identifier runs is not enough on
    /// its own: an attribute value may start with a digit, which <see cref="DbmlIdentifierRegex"/>
    /// (and dbdiagram.io) does not accept as the start of an identifier, so a leading underscore is
    /// added to keep the document parseable. The original is preserved in the group's note.
    /// </summary>
    private static string SlugifyGroupName(string groupName)
    {
        var slug = NonIdentifierRunRegex.Replace(groupName.Trim(), "_");

        return DbmlIdentifierRegex.IsMatch(slug) ? slug : $"_{slug}";
    }

    // ---- hiding --------------------------------------------------------------

    private static bool IsHidden(IEnumerable<AttributeModel> attributes)
    {
        return attributes.HasAttribute(DbmlErdAttributes.Hide);
    }

    // ---- escaping ------------------------------------------------------------

    /// <summary>
    /// Renders a model or field name as a DBML identifier. Attribute values are validated when they
    /// are parsed, but table and column names are not validated anywhere today and they reach this
    /// output too, so they are quoted here or rejected outright.
    /// </summary>
    private static string EscapeIdentifier(string name)
    {
        if (DbmlIdentifierRegex.IsMatch(name))
        {
            return name;
        }

        if (string.IsNullOrWhiteSpace(name) || name.Contains('"') || name.Any(char.IsControl))
        {
            throw new InvalidOperationException(
                $"'{name}' cannot be written as a DBML identifier.");
        }

        // A backslash escapes the next character inside a quoted DBML identifier, so a literal one
        // has to be doubled; otherwise a name ending in '\' would escape its own closing quote.
        return $"\"{name.Replace("\\", "\\\\")}\"";
    }

    /// <summary>
    /// Renders a DBML single-quoted string. DBML escapes a quote as <c>\'</c>, so the backslash has
    /// to be escaped first.
    /// </summary>
    private static string QuoteString(string value)
    {
        return $"'{value.Replace("\\", "\\\\").Replace("'", "\\'")}'";
    }

    // ---- output path ---------------------------------------------------------

    /// <summary>
    /// Resolves the output argument to the directory to create and the file to write. An argument
    /// ending in <c>.dbml</c> names the file; anything else is a directory that receives
    /// <see cref="DefaultFileName"/>.
    /// </summary>
    internal static (string Directory, string FilePath) ResolveOutputPath(string outputPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);

        var resolved = Path.GetFullPath(outputPath);

        if (resolved.EndsWith(DbmlFileExtension, StringComparison.OrdinalIgnoreCase))
        {
            // A rooted path ending in ".dbml" always has a containing directory.
            var parent = Path.GetDirectoryName(resolved)!;

            return (parent, EnsureWithinDirectory(parent, resolved));
        }

        return (resolved, EnsureWithinDirectory(resolved, Path.Combine(resolved, DefaultFileName)));
    }

    /// <summary>
    /// Asserts the file about to be written sits directly inside the resolved output root. Nothing
    /// author-controlled reaches the path today; this keeps that true if a future caller passes
    /// something composed.
    /// </summary>
    internal static string EnsureWithinDirectory(string directory, string filePath)
    {
        var fullDirectory = Path.GetFullPath(directory);
        var fullFilePath = Path.GetFullPath(filePath);

        var expected = Path.Combine(fullDirectory, Path.GetFileName(fullFilePath));

        if (!string.Equals(fullFilePath, expected, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"Refusing to write '{filePath}': it resolves outside the output directory '{fullDirectory}'.");
        }

        return fullFilePath;
    }
}