using Compile.Shift.Model;
using System.Text;

namespace Compile.Shift.Ef;

public class DbContextInterfaceGenerator
{
    public string GenerateDbContextInterface(DatabaseModel model, EfCodeGenerationOptions options)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file was generated by Shift.Ef code generator.");
        sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        sb.AppendLine();

        // Using statements
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {options.NamespaceName};");
        sb.AppendLine();

        // Interface declaration
        sb.AppendLine($"public partial interface {options.InterfaceName}");
        sb.AppendLine("{");

        // DbSet properties
        foreach (var table in model.Tables.Values)
        {
            sb.AppendLine($"    DbSet<{table.Name}Entity> {table.Name} {{ get; set; }}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}