// <auto-generated />
// This file was generated by Shift.Ef code generator.

using Compile.Shift.Ef.Demo;

public class Program
{
    public static async Task Main(string[] args)
    {
        await Demo.RunDemoAsync();
    }
}