using Compile.Shift.Model;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using static Compile.Shift.Dbml.Tests.TestModels;

namespace Compile.Shift.Dbml.Tests;

/// <summary>
/// Tests for <see cref="DbmlExporter"/>, the plugin that renders a loaded model as a DBML document
/// for dbdiagram.io.
///
/// Intent: every table becomes a Table block in Name order, every foreign key becomes one
/// standalone Ref oriented with the FK second, and the erd-* plugin attributes shape what is shown
/// (hiding, grouping, notes and colour) without any of that vocabulary leaking into Shift core.
/// </summary>
public class DbmlExporterTests
{
    private readonly DbmlExporter _sut = new() { Logger = NullLogger.Instance };

    private static DatabaseModel FullModel()
    {
        return Database(
            Table("User",
                fields:
                [
                    Field("UserID", "int", primaryKey: true, identity: true),
                    Field("Email", "nvarchar", precision: 256),
                    Field("DisplayName", "nvarchar", precision: 100, nullable: true),
                    Field("Balance", "decimal", precision: 12, scale: 2)
                ],
                indexes: [Index(unique: true, "Email")],
                attributes: [Attr("erd-note", "Application user"), Attr("erd-color", "#3498DB")]),
            Table("Invoice",
                fields:
                [
                    Field("InvoiceID", "int", primaryKey: true, identity: true),
                    Field("UserID", "int"),
                    Field("Reference", "varchar", precision: -1)
                ],
                foreignKeys: [ForeignKey("UserID", "User", "UserID")],
                attributes: [Attr("erd-group", "Billing Ops")]),
            Table("Payment",
                fields:
                [
                    Field("PaymentID", "int", primaryKey: true, identity: true),
                    Field("InvoiceID", "int"),
                    Field("Amount", "money")
                ],
                foreignKeys: [ForeignKey("InvoiceID", "Invoice", "InvoiceID", RelationshipType.OneToOne)],
                attributes: [Attr("erd-group", "Billing Ops")]));
    }

    [Fact]
    public Task GenerateDbml_WithFullModel_RendersTablesRefsAndGroups()
    {
        var dbml = _sut.GenerateDbml(FullModel());

        return Verify(dbml);
    }

    [Fact]
    public void GenerateDbml_WithEmptyModel_EmitsOnlyTheHeaderComment()
    {
        var dbml = _sut.GenerateDbml(new DatabaseModel());

        dbml.Trim().Should().Be("// Generated by Shift. Paste into https://dbdiagram.io to view the diagram.");
        dbml.Should().NotContain("Table ");
    }

    [Fact]
    public void GenerateDbml_TablesAreEmittedInNameOrder()
    {
        var dbml = _sut.GenerateDbml(Database(
            Table("Zebra", [Field("ZebraID", "int", primaryKey: true)]),
            Table("Apple", [Field("AppleID", "int", primaryKey: true)])));

        dbml.IndexOf("Table Apple", StringComparison.Ordinal)
            .Should().BeLessThan(dbml.IndexOf("Table Zebra", StringComparison.Ordinal));
    }

    // ---- @erd-hide -----------------------------------------------------------

    [Fact]
    public void GenerateDbml_HiddenModel_OmitsTheTableItsRefsAndItsGroupMembership()
    {
        var model = Database(
            Table("Secret",
                fields: [Field("SecretID", "int", primaryKey: true)],
                attributes: [Attr("erd-hide"), Attr("erd-group", "Billing")]),
            Table("Invoice",
                fields: [Field("InvoiceID", "int", primaryKey: true), Field("SecretID", "int")],
                foreignKeys: [ForeignKey("SecretID", "Secret", "SecretID")],
                attributes: [Attr("erd-group", "Billing")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().NotContain("Table Secret");
        dbml.Should().NotContain("Ref:");
        dbml.Should().Contain("TableGroup Billing");
        dbml.Should().NotContain("  Secret\n");
        dbml.Should().Contain("Invoice");
    }

    [Fact]
    public void GenerateDbml_HiddenField_OmitsTheColumnAndAnyRefUsingIt()
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true)]),
            Table("Invoice",
                fields:
                [
                    Field("InvoiceID", "int", primaryKey: true),
                    Field("UserID", "int", attributes: Attr("erd-hide")),
                    Field("Total", "money")
                ],
                foreignKeys: [ForeignKey("UserID", "User", "UserID")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("Total money");
        // The Invoice.UserID column is gone; User's own UserID primary key is untouched.
        dbml.Should().NotContain("  UserID int [not null]");
        dbml.Should().NotContain("Ref:");
    }

    [Fact]
    public void GenerateDbml_HiddenTargetColumn_DropsTheRefRatherThanDangling()
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true, attributes: Attr("erd-hide"))]),
            Table("Invoice",
                fields: [Field("InvoiceID", "int", primaryKey: true), Field("UserID", "int")],
                foreignKeys: [ForeignKey("UserID", "User", "UserID")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("Table User");
        dbml.Should().NotContain("Ref:");
    }

    [Fact]
    public void GenerateDbml_IndexNamingAHiddenColumn_IsOmitted()
    {
        var model = Database(Table("User",
            fields:
            [
                Field("UserID", "int", primaryKey: true),
                Field("TenantID", "int", attributes: Attr("erd-hide")),
                Field("Email", "nvarchar", precision: 256)
            ],
            indexes: [Index(unique: false, "Email", "TenantID")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().NotContain("indexes");
    }

    // ---- @erd-group ----------------------------------------------------------

    [Fact]
    public void GenerateDbml_Groups_OneTableGroupPerDistinctValueWithTheRightMembers()
    {
        var model = Database(
            Table("Invoice", [Field("InvoiceID", "int", primaryKey: true)], attributes: [Attr("erd-group", "Billing")]),
            Table("Payment", [Field("PaymentID", "int", primaryKey: true)], attributes: [Attr("erd-group", "billing")]),
            Table("Task", [Field("TaskID", "int", primaryKey: true)], attributes: [Attr("erd-group", "Work")]),
            Table("Loose", [Field("LooseID", "int", primaryKey: true)]));

        var dbml = _sut.GenerateDbml(model);

        // Grouping is case-insensitive, so "billing" joins "Billing".
        dbml.Should().Contain("TableGroup Billing {\n  Invoice\n  Payment\n}".ReplaceLineEndings());
        dbml.Should().Contain("TableGroup Work {\n  Task\n}".ReplaceLineEndings());
        dbml.Should().NotContain("Loose\n}".ReplaceLineEndings());
    }

    [Fact]
    public void GenerateDbml_TableWithoutGroup_IsInNoGroup()
    {
        var dbml = _sut.GenerateDbml(Database(
            Table("User", [Field("UserID", "int", primaryKey: true)])));

        dbml.Should().NotContain("TableGroup");
    }

    [Fact]
    public void GenerateDbml_GroupOnAField_IsIgnoredBecauseDbmlHasNoColumnGroups()
    {
        var model = Database(Table("User",
        [
            Field("UserID", "int", primaryKey: true),
            Field("Email", "nvarchar", precision: 256, attributes: Attr("erd-group", "Contact"))
        ]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().NotContain("TableGroup");
        dbml.Should().Contain("Email nvarchar(256)");
    }

    [Fact]
    public void GenerateDbml_GroupNameWithSpaces_IsSlugifiedWithTheOriginalInANote()
    {
        var model = Database(
            Table("Invoice", [Field("InvoiceID", "int", primaryKey: true)], attributes: [Attr("erd-group", "Billing Ops")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("TableGroup Billing_Ops [note: 'Billing Ops'] {");
    }

    [Fact]
    public void GenerateDbml_GroupNameNeedingNoSlug_HasNoRedundantNote()
    {
        var model = Database(
            Table("Invoice", [Field("InvoiceID", "int", primaryKey: true)], attributes: [Attr("erd-group", "Billing")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("TableGroup Billing {");
        dbml.Should().NotContain("note:");
    }

    // ---- @erd-note and @erd-color -------------------------------------------

    [Fact]
    public void GenerateDbml_ModelAndFieldNotes_AreEmitted()
    {
        var model = Database(Table("User",
            fields:
            [
                Field("UserID", "int", primaryKey: true),
                Field("Email", "nvarchar", precision: 256, attributes: Attr("erd-note", "PII"))
            ],
            attributes: [Attr("erd-note", "Application user")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("[not null, note: 'PII']");
        dbml.Should().Contain("Note: 'Application user'");
    }

    [Fact]
    public void GenerateDbml_NoteContainingAQuote_IsEscapedTheWayDbmlExpects()
    {
        var model = Database(Table("User",
            fields: [Field("UserID", "int", primaryKey: true)],
            attributes: [Attr("erd-note", "Chris's model")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain(@"Note: 'Chris\'s model'");
    }

    [Theory]
    [InlineData("#3498DB", " [headercolor: #3498DB]")]
    [InlineData("3498DB", " [headercolor: #3498DB]")]
    [InlineData("#38D", " [headercolor: #38D]")]
    public void GenerateDbml_Color_IsEmittedWithALeadingHash(string value, string expected)
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true)], attributes: [Attr("erd-color", value)]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain($"Table User{expected} {{");
    }

    [Theory]
    [InlineData("blue")]
    [InlineData("#12")]
    [InlineData("#1234567")]
    public void GenerateDbml_BadColor_Throws(string value)
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true)], attributes: [Attr("erd-color", value)]));

        var act = () => _sut.GenerateDbml(model);

        act.Should().Throw<InvalidOperationException>().WithMessage("*erd-color*User*");
    }

    // ---- column settings -----------------------------------------------------

    [Fact]
    public void GenerateDbml_ColumnSettings_RenderPkIncrementNotNullAndUnique()
    {
        var model = Database(Table("User",
            fields:
            [
                Field("UserID", "int", primaryKey: true, identity: true),
                Field("Email", "nvarchar", precision: 256),
                Field("Nickname", "nvarchar", precision: 50, nullable: true)
            ],
            indexes: [Index(unique: true, "Email")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("UserID int [pk, increment, not null]");
        dbml.Should().Contain("Email nvarchar(256) [not null, unique]");
        // Nullable is DBML's default, so a nullable column with no other setting has no settings list.
        dbml.Should().Contain("Nickname nvarchar(50)\n".ReplaceLineEndings());
    }

    [Fact]
    public void GenerateDbml_NonIdentityPrimaryKey_HasPkWithoutIncrement()
    {
        var model = Database(Table("User", [Field("UserID", "uniqueidentifier", primaryKey: true)]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("UserID uniqueidentifier [pk, not null]");
    }

    /// <summary>
    /// An unsupported type must reach the diagram verbatim rather than being dropped: a missing
    /// column is a silently wrong diagram, whereas an unfamiliar type name is merely unfamiliar.
    /// </summary>
    [Fact]
    public void GenerateDbml_UnsupportedColumnType_IsEmittedVerbatimRatherThanDropped()
    {
        var model = Database(Table("Place",
        [
            Field("PlaceID", "int", primaryKey: true),
            Field("Location", "geography"),
            Field("Extra", "user defined", nullable: true)
        ]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("Location geography [not null]");
        dbml.Should().Contain("Extra \"user defined\"");
    }

    // ---- indexes -------------------------------------------------------------

    [Fact]
    public void GenerateDbml_MultiColumnUniqueIndex_BecomesAnIndexesBlock()
    {
        var model = Database(Table("User",
            fields:
            [
                Field("UserID", "int", primaryKey: true),
                Field("TenantID", "int"),
                Field("Email", "nvarchar", precision: 256)
            ],
            indexes: [Index(unique: true, "TenantID", "Email"), Index(unique: false, "Email")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("  indexes {\n    (TenantID, Email) [unique]\n    Email\n  }".ReplaceLineEndings());
    }

    [Fact]
    public void GenerateDbml_DuplicateIndexes_AreEmittedOnce()
    {
        var model = Database(Table("User",
            fields: [Field("UserID", "int", primaryKey: true), Field("Email", "nvarchar", precision: 256)],
            indexes: [Index(unique: false, "Email"), Index(unique: false, "Email")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("indexes");
        System.Text.RegularExpressions.Regex.Matches(dbml, @"^    Email$",
            System.Text.RegularExpressions.RegexOptions.Multiline).Count.Should().Be(1);
    }

    [Fact]
    public void GenerateDbml_IndexNamingAModel_IsResolvedToTheForeignKeyColumn()
    {
        var model = Database(
            Table("Client", [Field("ClientID", "int", primaryKey: true)]),
            Table("Order",
                fields: [Field("OrderID", "int", primaryKey: true), Field("ClientID", "int")],
                foreignKeys: [ForeignKey("ClientID", "Client", "ClientID")],
                indexes: [Index(unique: false, "Client")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("    ClientID\n".ReplaceLineEndings());
    }

    // ---- relationships -------------------------------------------------------

    [Fact]
    public void GenerateDbml_Relationships_OrientTheForeignKeySecondWithTheRightCardinality()
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true)]),
            Table("Profile",
                fields: [Field("ProfileID", "int", primaryKey: true), Field("UserID", "int")],
                foreignKeys: [ForeignKey("UserID", "User", "UserID", RelationshipType.OneToOne)]),
            Table("Task",
                fields: [Field("TaskID", "int", primaryKey: true), Field("OwnerUserID", "int")],
                foreignKeys: [ForeignKey("OwnerUserID", "User", "UserID", RelationshipType.OneToMany)]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("Ref: User.UserID - Profile.UserID");
        dbml.Should().Contain("Ref: User.UserID < Task.OwnerUserID");
    }

    [Fact]
    public void GenerateDbml_Relationships_AreEmittedAfterEveryTable()
    {
        var model = Database(
            Table("User", [Field("UserID", "int", primaryKey: true)]),
            Table("Task",
                fields: [Field("TaskID", "int", primaryKey: true), Field("UserID", "int")],
                foreignKeys: [ForeignKey("UserID", "User", "UserID")]));

        var dbml = _sut.GenerateDbml(model);

        dbml.IndexOf("Ref:", StringComparison.Ordinal)
            .Should().BeGreaterThan(dbml.LastIndexOf("Table ", StringComparison.Ordinal));
    }

    // ---- identifiers ---------------------------------------------------------

    [Fact]
    public void GenerateDbml_NameNeedingQuoting_IsQuoted()
    {
        var model = Database(Table("User Profile", [Field("User ID", "int", primaryKey: true)]));

        var dbml = _sut.GenerateDbml(model);

        dbml.Should().Contain("Table \"User Profile\" {");
        dbml.Should().Contain("\"User ID\" int");
    }

    [Fact]
    public void GenerateDbml_NameContainingADoubleQuote_Throws()
    {
        var model = Database(Table("Bad\"Name", [Field("Id", "int", primaryKey: true)]));

        var act = () => _sut.GenerateDbml(model);

        act.Should().Throw<InvalidOperationException>().WithMessage("*DBML identifier*");
    }
}